
version: '3.8'
services:

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    env_file:
      - .env
    volumes:
      - mongo-data:/data/db
    networks:
      - node-sample-app

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - node-sample-app

  backend:
    build: .
    container_name: backend
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - uploads:/usr/src/app/storage/uploads
    networks:
      - node-sample-app

networks:
  node-sample-app:
    driver: bridge

volumes:
  mongo-data:
  rabbitmq-data:
  uploads: